project:
  type: website

website:
  title: "Telkom Digital Amoeba - VIX Talent Database"
  navbar:
    background: primary
    left:
      - href: ux.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

